package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/telleroutlook/proofctl/internal/config"
	errors "github.com/telleroutlook/proofctl/internal/errors"
)

// envLock is the structure of environment.lock JSON files.
type envLock struct {
	GeneratedAt   string            `json:"generated_at"`
	Checker       string            `json:"checker"`
	PythonVersion string            `json:"python_version,omitempty"`
	Packages      map[string]string `json:"packages,omitempty"`
	Note          string            `json:"note,omitempty"`
}

func cmdEnv(args []string, useJSON bool) {
	if len(args) == 0 {
		die(useJSON, errors.CodeInvalidInput, "usage: proofctl env <verify|snapshot>")
	}
	switch args[0] {
	case "verify":
		cmdEnvVerify(args[1:], useJSON)
	case "snapshot":
		cmdEnvSnapshot(args[1:], useJSON)
	default:
		die(useJSON, errors.CodeInvalidInput, "unknown env subcommand "+args[0]+"; use verify or snapshot")
	}
}

func cmdEnvVerify(args []string, useJSON bool) {
	fs := flag.NewFlagSet("env verify", flag.ContinueOnError)
	lockFlag := fs.String("lock", "environment.lock", "path to environment lock file")
	if err := fs.Parse(args); err != nil {
		die(useJSON, errors.CodeInvalidInput, err.Error())
	}

	data, err := os.ReadFile(*lockFlag)
	if err != nil {
		die(useJSON, errors.CodeInvalidInput, "cannot read lock file: "+err.Error())
	}
	var lock envLock
	if err := json.Unmarshal(data, &lock); err != nil {
		die(useJSON, errors.CodeInvalidInput, "cannot parse lock file: "+err.Error())
	}

	type checkEntry struct {
		Name   string `json:"name"`
		Locked string `json:"locked"`
		Found  string `json:"found"`
		Match  bool   `json:"match"`
	}
	var checks []checkEntry
	pass := true

	// Check Python version if recorded.
	if lock.PythonVersion != "" && lock.Checker != "" {
		checkerBin := strings.Fields(lock.Checker)[0]
		out, err := exec.Command(checkerBin, "--version").CombinedOutput()
		found := ""
		if err != nil {
			found = fmt.Sprintf("[ERROR: cannot run %s: %v]", checkerBin, err)
		} else {
			found = strings.TrimSpace(string(out))
		}
		match := found == lock.PythonVersion
		if !match {
			pass = false
		}
		checks = append(checks, checkEntry{
			Name:   "python_version",
			Locked: lock.PythonVersion,
			Found:  found,
			Match:  match,
		})
	}

	// Check package versions via pip show.
	for pkg, lockedVer := range lock.Packages {
		found := pipShowVersion(lock.Checker, pkg)
		match := found == lockedVer
		if !match {
			pass = false
		}
		checks = append(checks, checkEntry{
			Name:   pkg,
			Locked: lockedVer,
			Found:  found,
			Match:  match,
		})
	}

	if useJSON {
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		_ = enc.Encode(map[string]any{"pass": pass, "checks": checks})
		return
	}
	fmt.Printf("%-30s  %-20s  %-20s  %s\n", "PACKAGE", "LOCKED", "FOUND", "STATUS")
	fmt.Printf("%-30s  %-20s  %-20s  %s\n", strings.Repeat("-", 30), strings.Repeat("-", 20), strings.Repeat("-", 20), "------")
	for _, c := range checks {
		status := "OK"
		if !c.Match {
			status = "MISMATCH"
		}
		fmt.Printf("%-30s  %-20s  %-20s  %s\n", c.Name, c.Locked, c.Found, status)
	}
	if pass {
		fmt.Println("\nenv verify: PASS")
	} else {
		fmt.Println("\nenv verify: FAIL — environment does not match lock file")
		os.Exit(1)
	}
}

func cmdEnvSnapshot(args []string, useJSON bool) {
	fs := flag.NewFlagSet("env snapshot", flag.ContinueOnError)
	checkerFlag := fs.String("checker", "python3", "checker interpreter (e.g. python3)")
	outFlag := fs.String("out", "environment.lock", "output lock file path")
	if err := fs.Parse(args); err != nil {
		die(useJSON, errors.CodeInvalidInput, err.Error())
	}

	lock := envLock{
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
		Checker:     *checkerFlag,
		Packages:    make(map[string]string),
		Note:        "generated by proofctl env snapshot — verify with: proofctl env verify --lock " + *outFlag,
	}

	// Get Python version.
	checkerBin := strings.Fields(*checkerFlag)[0]
	if out, err := exec.Command(checkerBin, "--version").CombinedOutput(); err == nil {
		lock.PythonVersion = strings.TrimSpace(string(out))
	} else {
		fmt.Fprintf(os.Stderr, "warn: cannot get version from %s: %v — python_version not recorded in snapshot\n", checkerBin, err)
	}

	// Get installed packages via pip freeze.
	pipBin := derivePip(*checkerFlag)
	if out, err := exec.Command(pipBin, "freeze").Output(); err == nil {
		scanner := bufio.NewScanner(strings.NewReader(string(out)))
		for scanner.Scan() {
			line := strings.TrimSpace(scanner.Text())
			if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "-") {
				continue
			}
			// Handle both pkg==ver and pkg @ url forms.
			if idx := strings.Index(line, "=="); idx != -1 {
				pkg := strings.ToLower(line[:idx])
				ver := line[idx+2:]
				lock.Packages[pkg] = ver
			}
		}
	} else {
		fmt.Fprintf(os.Stderr, "warn: cannot run %s freeze: %v — packages not recorded in snapshot\n", pipBin, err)
	}

	data, _ := json.MarshalIndent(lock, "", "  ")
	data = append(data, '\n')
	if err := os.WriteFile(*outFlag, data, 0o644); err != nil {
		die(useJSON, errors.CodeInternalError, "cannot write lock file: "+err.Error())
	}

	if useJSON {
		enc := json.NewEncoder(os.Stdout)
		_ = enc.Encode(map[string]any{
			"written":        *outFlag,
			"checker":        *checkerFlag,
			"python_version": lock.PythonVersion,
			"package_count":  len(lock.Packages),
		})
		return
	}
	pkgNote := fmt.Sprintf("%d recorded", len(lock.Packages))
	if len(lock.Packages) == 0 {
		pkgNote = "0 recorded (pip freeze may have failed — check warnings above)"
	}
	fmt.Printf("Snapshot written to %s\n", *outFlag)
	fmt.Printf("Python: %s\n", lock.PythonVersion)
	fmt.Printf("Packages: %s\n", pkgNote)
	fmt.Printf("Run 'proofctl env verify --lock %s' to check the environment.\n", *outFlag)
}

// autoLoadEnv reads .proofctl/env in the nearest project root and sets any
// KEY=VALUE lines as environment variables, skipping already-set variables.
// It is called at startup so that BRIDGE_CHECKER, PROOFCTL_ADAPTERS, etc.
// don't need to be re-exported every session.
//
// File format: one KEY=VALUE per line; blank lines and lines starting with #
// are ignored. Values may optionally be quoted with single or double quotes.
func autoLoadEnv() {
	cwd, err := os.Getwd()
	if err != nil {
		return
	}
	root, err := findProjectRoot(cwd)
	if err != nil {
		return
	}
	envFile := filepath.Join(root, config.DirName, "env")
	data, err := os.ReadFile(envFile)
	if err != nil {
		return // no env file — silently skip
	}
	scanner := bufio.NewScanner(strings.NewReader(string(data)))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		idx := strings.IndexByte(line, '=')
		if idx < 1 {
			continue
		}
		key := strings.TrimSpace(line[:idx])
		val := strings.TrimSpace(line[idx+1:])
		// Strip optional surrounding quotes.
		if len(val) >= 2 && ((val[0] == '"' && val[len(val)-1] == '"') ||
			(val[0] == '\'' && val[len(val)-1] == '\'')) {
			val = val[1 : len(val)-1]
		}
		// Only set if not already in environment.
		if os.Getenv(key) == "" {
			_ = os.Setenv(key, val)
		}
	}
}

// findProjectRoot walks up from dir looking for .proofctl/.
// It is a lightweight duplicate of config.Find used here to avoid import cycles.
func findProjectRoot(dir string) (string, error) {
	for {
		if _, err := os.Stat(filepath.Join(dir, ".proofctl")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no .proofctl found")
		}
		dir = parent
	}
}

// using the pip binary derived from the checker path.
// Returns "[pip-error: ...]" if pip cannot be run, so the caller can distinguish
// a broken pip from a genuinely absent package.
func pipShowVersion(checker, pkg string) string {
	pipBin := derivePip(checker)
	out, err := exec.Command(pipBin, "show", pkg).Output()
	if err != nil {
		// Distinguish "package not installed" (exit 1, no output) from "pip broken".
		if exitErr, ok := err.(*exec.ExitError); ok && exitErr.ExitCode() == 1 && len(out) == 0 {
			return ""
		}
		return fmt.Sprintf("[pip-error: cannot run %s show %s: %v]", pipBin, pkg, err)
	}
	for _, line := range strings.Split(string(out), "\n") {
		if strings.HasPrefix(strings.ToLower(line), "version:") {
			return strings.TrimSpace(line[len("Version:"):])
		}
	}
	return ""
}

// derivePip infers the pip binary from the checker interpreter path.
// "python3" → "pip3", "python" → "pip", "/usr/bin/python3.12" → "pip3".
func derivePip(checker string) string {
	base := checker
	if idx := strings.LastIndex(checker, "/"); idx >= 0 {
		base = checker[idx+1:]
	}
	base = strings.Fields(base)[0]
	switch {
	case strings.HasPrefix(base, "python3"):
		return "pip3"
	case strings.HasPrefix(base, "python"):
		return "pip"
	default:
		return "pip3"
	}
}
