package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strings"

	errors "github.com/telleroutlook/proofctl/internal/errors"
	"github.com/telleroutlook/proofctl/internal/ir"
)

func cmdExport(args []string, useJSON bool) {
	fs := flag.NewFlagSet("export", flag.ContinueOnError)
	claimFlag := fs.String("claim", "", "claim ID to export")
	formatFlag := fs.String("format", "lean", "output format (lean)")
	outFlag := fs.String("out", "", "output file path (default: ProofCtlImport_<claim-id>.<ext>)")
	if err := fs.Parse(args); err != nil {
		die(useJSON, errors.CodeInvalidInput, err.Error())
	}
	if *claimFlag == "" {
		die(useJSON, errors.CodeInvalidInput, "export: --claim is required")
	}
	if *formatFlag != "lean" {
		die(useJSON, errors.CodeInvalidInput, fmt.Sprintf("export: unsupported format %q (supported: lean)", *formatFlag))
	}

	root, _, _, attestations := loadProjectGraph(useJSON)

	att, ok := attestations[*claimFlag]
	if !ok {
		die(useJSON, errors.CodeInvalidInput, fmt.Sprintf("export: no attestation found for claim %q", *claimFlag))
	}
	if att.Outcome != string(ir.StatusAccepted) {
		die(useJSON, errors.CodeInvalidInput, fmt.Sprintf("export: claim %q is not accepted (outcome: %s)", *claimFlag, att.Outcome))
	}

	switch *formatFlag {
	case "lean":
		outPath := *outFlag
		if outPath == "" {
			outPath = "ProofCtlImport_" + sanitizeClaimID(*claimFlag) + ".lean"
		}
		if err := exportLean(root, *claimFlag, att, outPath, useJSON); err != nil {
			die(useJSON, errors.CodeInternalError, "export: "+err.Error())
		}
	}
}

// exportLean writes a Lean 4 axiom file for the given accepted attestation.
func exportLean(root, claimID string, att *ir.Attestation, outPath string, useJSON bool) error {
	// Build axiom name from claim ID: thm-main-radius-030 → weil_main_radius_030
	axiomName := claimIDToLeanName(claimID)

	// Extract statement text from the DAG for the comment.
	statementText := claimID // fallback
	pg := loadRawGraph(root, useJSON)
	for _, c := range pg.Claims {
		if c.ID == claimID {
			statementText = c.Statement.Text
			break
		}
	}

	var sb strings.Builder
	sb.WriteString("-- Auto-generated by proofctl. DO NOT EDIT.\n")
	sb.WriteString("-- Source claim: " + claimID + "\n")
	sb.WriteString("-- Attestation digest: " + att.SelfDigest + "\n")
	sb.WriteString("-- Statement digest: " + att.StatementDigest + "\n")
	sb.WriteString("-- Assurance: " + string(att.Assurance) + "\n")
	sb.WriteString("-- Generated: " + att.StartFreshness + "\n")
	sb.WriteString("\n")
	sb.WriteString("namespace ProofCtlImport\n")
	sb.WriteString("\n")
	sb.WriteString("/-\n")
	sb.WriteString("  " + statementText + "\n")
	sb.WriteString("-/\n")
	sb.WriteString("axiom " + axiomName + " : True -- replace with actual Lean 4 type\n")
	sb.WriteString("\n")
	sb.WriteString("end ProofCtlImport\n")

	content := []byte(sb.String())

	if err := os.WriteFile(outPath, content, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}

	if useJSON {
		enc := json.NewEncoder(os.Stdout)
		_ = enc.Encode(map[string]string{
			"claim_id":           claimID,
			"attestation_digest": att.SelfDigest,
			"format":             "lean",
			"output":             outPath,
			"axiom_name":         axiomName,
		})
	} else {
		fmt.Printf("Exported claim %q to %s\n", claimID, outPath)
		fmt.Printf("  attestation: %s\n", att.SelfDigest)
		fmt.Printf("  axiom:       ProofCtlImport.%s\n", axiomName)
	}
	return nil
}

// sanitizeClaimID converts a claim ID to a safe filename component.
func sanitizeClaimID(id string) string {
	return strings.NewReplacer("/", "-", ":", "-", " ", "-").Replace(id)
}

// claimIDToLeanName converts a claim ID to a valid Lean 4 identifier.
// thm-main-radius-030  →  thm_main_radius_030
func claimIDToLeanName(id string) string {
	// Replace hyphens and dots with underscores; strip other non-alnum chars.
	var b strings.Builder
	for _, r := range id {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}
